export const signData = [
    {
        id: 1,
        imageUrl: "/images/signs/1.jpg",
        correctAns: 4,
        options: [
            "Road slippery when wet",
            "No left turn permitted",
            "No right turn permitted",
            "You must not make a 'U' turn",
        ],
    },
    {
        id: 2,
        imageUrl: "/images/signs/2.jpg",
        correctAns: 2,
        options: [
            "Hidden instruction ahead",
            "Winding road",
            "Road slippery when wet",
            "Narrow road ahead",
        ],
    },
    {
        id: 3,
        imageUrl: "/images/signs/3.jpg",
        correctAns: 2,
        options: [
            "No entry into the intersection",
            "This is sign means no stopping",
            "Vehicles approaching from angle shown, must stop",
            "Need not to stop for stop sign in direction of arrow",
        ],
    },
    {
        id: 4,
        imageUrl: "/images/signs/4.jpg",
        correctAns: 1,
        options: [
            "Traffic signal ahead",
            "Stop sign 150 meters (500 feet) ahead",
            "Bump 120 meters (400 feet) ahead",
            "Railway crossing ahead",
        ],
    },
    {
        id: 5,
        imageUrl: "/images/signs/5.jpg",
        correctAns: 3,
        options: [
            "Winding road ahead",
            "Bumpy road ahead",
            "Road ahead slippery when wet",
            "No passing ahead",
        ],
    },
    {
        id: 6,
        imageUrl: "/images/signs/6.jpg",
        correctAns: 3,
        options: [
            "Playground zone sign",
            "Children playing in residential area",
            "School zone sign",
            "Directions sign for children",
        ],
    },
    {
        id: 7,
        imageUrl: "/images/signs/7.jpg",
        correctAns: 4,
        options: [
            "Divided highway ahead",
            "You are approaching a one-Way Street",
            "Hidden instruction ahead",
            "Pavement narrows",
        ],
    },
    {
        id: 8,
        imageUrl: "/images/signs/8.jpg",
        correctAns: 4,
        options: [
            "Narrow rd head",
            "Railway crossing ahead",
            "Hidden instruction ahead",
            "Intersection ahead",
        ],
    },
    {
        id: 9,
        imageUrl: "/images/signs/9.jpg",
        correctAns: 2,
        options: [
            "Divided highway ahead",
            "Divided road ends, keep to the right",
            "Narrow bridge ahead",
            "Road under construction",
        ],
    },
    {
        id: 10,
        imageUrl: "/images/signs/10.jpg",
        correctAns: 4,
        options: [
            "Right Lane ends",
            "Hidden instruction ahead",
            "You are approaching a steep hill",
            "Passing is not allowed",
        ],
    },
    {
        id: 11,
        imageUrl: "/images/signs/11.png",
        correctAns: 3,
        options: [
            "Narrow rd ahead",
            "Road ahead turns left then right",
            "Road ahead turns right then left",
            "Intersection ahead",
        ],
    },
    {
        id: 12,
        imageUrl: "/images/signs/12.jpg",
        correctAns: 1,
        options: [
            "Stop sign ahead",
            "Yield right of way",
            "Dead end straight ahead",
            "Slow moving vehicle ahead",
        ],
    },
    {
        id: 13,
        imageUrl: "/images/signs/13.png",
        correctAns: 4,
        options: [
            "Truck route",
            "No tracks",
            "Route for large trucks",
            "Permissive sign",
        ],
    },
    {
        id: 14,
        imageUrl: "/images/signs/14.jpg",
        correctAns: 3,
        options: [
            "Keep to right",
            "Keep to left",
            "Keep out(Do not enter)",
            "Do not pass",
        ],
    },
    {
        id: 15,
        imageUrl: "/images/signs/15.jpg",
        correctAns: 4,
        options: [
            "Construction sign--slow down obey flagman direction",
            "A construction sign replacing flagman on duty",
            "Regulatory sign--reduce speed",
            "This sign warns of road work operation ahead",
        ],
    },
    {
        id: 16,
        imageUrl: "/images/signs/16.png",
        correctAns: 4,
        options: [
            "Policemen at intersection",
            "You will get a ticket if you do not obey traffic signal",
            "Stop for light at intersection",
            "Red light camera at intersection",
        ],
    },
    {
        id: 17,
        imageUrl: "/images/signs/17.jpg",
        correctAns: 1,
        options: [
            "Deer regularly cross, be alert for animals",
            "Zoo ahead",
            "No honking at animals",
            "Deers are welcome",
        ],
    },
    {
        id: 18,
        imageUrl: "/images/signs/18.jpg",
        correctAns: 1,
        options: [
            "Truck entrance on the right side ahead",
            "No truck allows",
            "Slow down for truck",
            "Tuck route",
        ],
    },
    {
        id: 19,
        imageUrl: "/images/signs/19.jpg",
        correctAns: 2,
        options: [
            "Narrow bridge ahead",
            "No right turn on red",
            "No right turn",
            "Divided highway ends",
        ],
    },
    {
        id: 20,
        imageUrl: "/images/signs/20.png",
        correctAns: 3,
        options: [
            "You may exit if you remain in right hand lane",
            "You may not drive in right hand lane under any circumstances",
            "Two-way left turn lane",
            "End of highway, you must move into right hand lane",
        ],
    },
    {
        id: 21,
        imageUrl: "/images/signs/21.jpg",
        correctAns: 4,
        options: [
            "X-intersection for school vehicles",
            "School crosswalk sign",
            "Caution--school bus crossing",
            "Regulatory sign",
        ],
    },
    {
        id: 22,
        imageUrl: "/images/signs/22.png",
        correctAns: 3,
        options: [
            "School area ahead",
            "Railway crossing ahead",
            "You must give the right-of-way",
            "you have the right-of-way",
        ],
    },
    {
        id: 23,
        imageUrl: "/images/signs/23.jpg",
        correctAns: 3,
        options: [
            "Stop sign 150 meters (500 feet) ahead",
            "Bump 120 meters (400 feet) ahead",
            "Stop at all times",
            "Stop only if other vehicles are approaching",
        ],
    },
    {
        id: 24,
        imageUrl: "/images/signs/24.jpg",
        correctAns: 2,
        options: [
            "You must make a right turn only",
            "You must not make a left turn",
            "Hidden intersection ahead",
            "You are approaching a traffic island",
        ],
    },
    {
        id: 25,
        imageUrl: "/images/signs/25.png",
        correctAns: 3,
        options: [
            "No Bicycles allowed",
            "Do not drive through",
            "Bicycle route",
            "No parking",
        ],
    },
    {
        id: 26,
        imageUrl: "/images/signs/26.jpg",
        correctAns: 3,
        options: [
            "Snowmobiles may not use this road",
            "Snowmobiles parking only",
            "Snowmobiles may use this road",
            "Snowmobiles repair shop ahead",
        ],
    },
    {
        id: 27,
        imageUrl: "/images/signs/27.jpeg",
        correctAns: 1,
        options: [
            "You may park in the designated area during the posted times",
            "You may not park between the signs during the posted times",
            "NO parking",
            "Weekend parking only",
        ],
    },
    {
        id: 28,
        imageUrl: "/images/signs/28.jpg",
        correctAns: 2,
        options: [
            "Bicycles are allowed on tis road",
            "No bicycles allowed on this road",
            "No parking",
            "No stopping",
        ],
    },
    {
        id: 29,
        imageUrl: "/images/signs/29.jpg",
        correctAns: 3,
        options: [
            "Care for pedestrian",
            "Watch for traffic signal",
            "Do not block intersection",
            "Do not slow down",
        ],
    },
    {
        id: 30,
        imageUrl: "/images/signs/30.webp",
        correctAns: 1,
        options: [
            "The lane is reserved for specific types of vehicles during certain times and days such as buses, taxis, bicycles and other vehicles",
            "No buses allowed on the specified lane during times and days psoted",
            "No stopping during the times and days posted",
            "Do not enter between the times and days posted",
        ],
    },
    {
        id: 31,
        imageUrl: "/images/signs/31.png",
        correctAns: 2,
        options: [
            "Intersection ahead",
            "Narrow bridge ahead",
            "Paved surface ends ahead",
            "The road ahead is split",
        ],
    },
    {
        id: 32,
        imageUrl: "/images/signs/32.png",
        correctAns: 1,
        options: [
            "Keep to the right of the traffic island",
            "Road turns right then left",
            "Winding road ahead",
            "Pass other traffic on the right",
        ],
    },
    {
        id: 33,
        imageUrl: "/images/signs/33.jpeg",
        correctAns: 1,
        options: [
            "Destination board",
            "School zone--watch for children playing",
            "Provincial park",
            "Pedestrian control sign",
        ],
    },
    {
        id: 34,
        imageUrl: "/images/signs/34.jpg",
        correctAns: 4,
        options: [
            "Stop sign ahead",
            "Yield right-of-way",
            "Dead end street ahead",
            "Slow moving vehicle",
        ],
    },
    {
        id: 35,
        imageUrl: "/images/signs/35.png",
        correctAns: 4,
        options: [
            "Going straight is allowed",
            "No right turn",
            "No left turn",
            "Do not drive straight through the intersection",
        ],
    },
    {
        id: 36,
        imageUrl: "/images/signs/36.jpeg",
        correctAns: 1,
        options: [
            "Parking is only vehicles displaying a valid disabled person parking permit",
            "No parking",
            "No standing",
            "Parking is not allowed for a disable person with a permit",
        ],
    },
    {
        id: 37,
        imageUrl: "/images/signs/37.jpg",
        correctAns: 2,
        options: [
            "No bicycles",
            "No pedestrians allowed",
            "No children allowed",
            "Dogs only",
        ],
    },
    {
        id: 38,
        imageUrl: "/images/signs/38.jpg",
        correctAns: 1,
        options: [
            "Only for picking up and dropping off passengers if you have a disabled persons permit",
            "Standing area for disabled persons only",
            "No parking",
            "Parking is permitted",
        ],
    },
    {
        id: 39,
        imageUrl: "/images/signs/39.jpg",
        correctAns: 3,
        options: [
            "School area",
            "Bumpy road",
            "Do not stand or stop in this area",
            "No bicycles allowed on this road",
        ],
    },
    {
        id: 40,
        imageUrl: "/images/signs/40.png",
        correctAns: 4,
        options: [
            "This lane is for buses only",
            "This lane is for trucks only",
            "This lane is not for bicycles",
            "This lane is for bicycles only",
        ],
    },
    {
        id: 41,
        imageUrl: "/images/signs/41.png",
        correctAns: 1,
        options: [
            "Keep to the right lane except when passing (for climbing lanes)",
            "Keep right if you want to park",
            "No U-turn",
            "For right turns",
        ],
    },
    {
        id: 42,
        imageUrl: "/images/signs/42.png",
        correctAns: 3,
        options: [
            "No left turns",
            "Merging traffic ahead",
            "Road branching off ahead",
            "Hidden intersection",
        ],
    },
    {
        id: 43,
        imageUrl: "/images/signs/43.jpg",
        correctAns: 4,
        options: [
            "No U-turn",
            "No left turns",
            "Right turn ahead",
            "The side-road at the intersection ahead does not have a clear view of traffic",
        ],
    },
    {
        id: 44,
        imageUrl: "/images/signs/44.png",
        correctAns: 4,
        options: [
            "Do not enter roadway",
            "Do not enter unless local traffic",
            "A traffic circle ahead",
            "Prohibited sign",
        ],
    },
    {
        id: 45,
        imageUrl: "/images/signs/45.png",
        correctAns: 1,
        options: [
            "Merge with traffic, two roads are equally responsible",
            "Hidden intersection",
            "No U-turn",
            "Prohibited sign",
        ],
    },
    {
        id: 46,
        imageUrl: "/images/signs/46.webp",
        correctAns: 1,
        options: [
            "Paved surface ends ahead",
            "Watch for falling rocks",
            "School zone sign",
            "Do not block intersection",
        ],
    },
    {
        id: 47,
        imageUrl: "/images/signs/47.png",
        correctAns: 2,
        options: [
            "Bicycle surface ends ahead",
            "Watch for falling rocks",
            "School zone sign",
            "Do not block intersection",
        ],
    },
    {
        id: 48,
        imageUrl: "/images/signs/48.png",
        correctAns: 2,
        options: [
            "Safety check ahead",
            "Warns of a steep hill ahead",
            "Pavement ends, 500 feet ahead",
            "Bumpy road ahead",
        ],
    },
    {
        id: 49,
        imageUrl: "/images/signs/49.jpg",
        correctAns: 1,
        options: [
            "Right lane ends",
            "HIdden intersection ahead",
            "You are approaching a steep hill",
            "No parking",
        ],
    },
    {
        id: 50,
        imageUrl: "/images/signs/50.png",
        correctAns: 4,
        options: [
            "Winding road ahead",
            "Keep to left",
            "Danger, road ends",
            "DAnger, sharp turn",
        ],
    },
    {
        id: 51,
        imageUrl: "/images/signs/51.png",
        correctAns: 2,
        options: [
            "You are approaching a four-way intersection",
            "You are approaching a railroad crossing",
            "You are approaching a hospital zone",
            "You are approaching a pedestrian crosswalk",
        ],
    },
    {
        id: 52,
        imageUrl: "/images/signs/52.jpeg",
        correctAns: 4,
        options: [
            "Maximum seed of 50 km (30 miles) per hour from this sign to the next sign",
            "Speed limit for rural school zones",
            "End of 50 km (30 miles) per hour zone",
            "Maximum speed of 50 km (30 miles) per hour ahead",
        ],
    },
    {
        id: 53,
        imageUrl: "/images/signs/53.jpg",
        correctAns: 2,
        options: [
            "I am turning left",
            "I am slowing or stopping",
            "I am turning right",
            "You may pass now",
        ],
    },
    {
        id: 54,
        imageUrl: "/images/signs/54.webp",
        correctAns: 2,
        options: [
            "Factory ahead, slow down",
            "Bumpy or uneven pavement ahead",
            "Construction zone",
            "Bridge or viaduct",
        ],
    },
    {
        id: 55,
        imageUrl: "/images/signs/55.jpeg",
        correctAns: 1,
        options: [
            "I am turning right",
            "I am turning left",
            "I am slowing or stopping",
            "You may pass me",
        ],
    },
    {
        id: 56,
        imageUrl: "/images/signs/56.webp",
        correctAns: 4,
        options: [
            "You may exit if you remain in right hand lane",
            "You must not drive in right hand lane under any circumstances",
            "End of highway, you must move into right hand lane",
            "You must exit if you remain in right hand lane",
        ],
    },
    {
        id: 57,
        imageUrl: "/images/signs/57.png",
        correctAns: 2,
        options: [
            "Drive with caution",
            "Share the road with oncoming traffic",
            "Slippery when wet",
            "No standing",
        ],
    },
    {
        id: 58,
        imageUrl: "/images/signs/58.png",
        correctAns: 2,
        options: [
            "No truck allowed",
            "Warns of a steep hill ahead",
            "Passing is not allowed",
            "Watch for falling rocks",
        ],
    },
    {
        id: 59,
        imageUrl: "/images/signs/59.png",
        correctAns: 3,
        options: [
            "Fire hall",
            "Do not enter",
            "There may be water flowing ove the road",
            "Construction zone",
        ],
    },
    {
        id: 60,
        imageUrl: "/images/signs/60.webp",
        correctAns: 1,
        options: [
            "A hidden school but zone ahead, slow down, drive with extra caution, watch for children and school buses with flashing red light",
            "Hidden intersection",
            "School zone",
            "School with play ground",
        ],
    },
    {
        id: 61,
        imageUrl: "/images/signs/61.jpg",
        correctAns: 2,
        options: [
            "Bumpy road ahead",
            "Sign shows the maximum truck clearance height",
            "Shool zone ahead",
            "Watch for falling rocks",
        ],
    },
    {
        id: 62,
        imageUrl: "/images/signs/62.webp",
        correctAns: 3,
        options: [
            "Snowmobile repair shop ahead",
            "Snowmobile parking",
            "Snowmobile cross the road",
            "Snowmobile not allowed",
        ],
    },
    {
        id: 63,
        imageUrl: "/images/signs/63.png",
        correctAns: 1,
        options: [
            "Do not pass any vehicles within 30 metres of pedestrian crossing",
            "School zone",
            "Uneven pavement ahead",
            "Construction zone",
        ],
    },
    {
        id: 64,
        imageUrl: "/images/signs/64.jpeg",
        correctAns: 4,
        options: [
            "Watch for disabled persons",
            "Passing is not allowed",
            "Wheel chair crossing",
            "A school crossing ahead, follow the direction of the crossing guard or school safety patroller",
        ],
    },
    {
        id: 65,
        imageUrl: "/images/signs/65.jpg",
        correctAns: 1,
        options: [
            "when a school bus arm swings out with red lights flashing, you must stop and you are prohibited from passing",
            "Construction sign",
            "School zone",
            "Stop sign ahead",
        ],
    },
    {
        id: 66,
        imageUrl: "/images/signs/66.jpg",
        correctAns: 2,
        options: [
            "It is warning sign",
            "During school hours when the yellow lights are flashing, follow the speed limit shown",
            "Watch for cross guard only",
            "Watch for children only",
        ],
    },
    {
        id: 67,
        imageUrl: "/images/signs/67.png",
        correctAns: 3,
        options: [
            "Highway with two express lanes",
            "The two lanes ahead are closed",
            "Two or more passengers must be in the vehicle to use this lane on the highway",
            "Two lanes will merge into one",
        ],
    },
    {
        id: 68,
        imageUrl: "/images/signs/68.jpg",
        correctAns: 1,
        options: [
            "Hazard, the downward line indicates the side on which you may safely pass",
            "Hazard, the downward line indicates the side on which you may not safely pass",
            "Shopping ahead",
            "Rest area ahead",
        ],
    },
    {
        id: 69,
        imageUrl: "/images/signs/69.png",
        correctAns: 2,
        options: [
            "Winding road ahead",
            "By wheel-chair only or disabled person parking(handicap)",
            "No parking",
            "No standing",
        ],
    },
    {
        id: 70,
        imageUrl: "/images/signs/70.jpg",
        correctAns: 1,
        options: [
            "Two separate roads by median ahead, keep to the right",
            "Divided highway ends",
            "Narrow bridge ahead",
            "Road under construction",
        ],
    },
    {
        id: 71,
        imageUrl: "/images/signs/71.jpg",
        correctAns: 4,
        options: [
            "Lane usage sign permitting all turns including left",
            "No parking from arrow to corner",
            "Advance warning of danger",
            "Lane usage sign meaning right turn only",
        ],
    },
    {
        id: 72,
        imageUrl: "/images/signs/72.jpg",
        correctAns: 2,
        options: [
            "I am turning right",
            "I am turning left",
            "I am slowing or stopping",
            "I am stopping",
        ],
    },
    {
        id: 73,
        imageUrl: "/images/signs/73.jpg",
        correctAns: 3,
        options: [
            "Keep distance away",
            "New born baby on broad",
            "New driver",
            "New car",
        ],
    },
    {
        id: 74,
        imageUrl: "/images/signs/74.jpg",
        correctAns: 2,
        options: ["Housing", "Hospital", "Horse racing", "Hills"],
    },
    {
        id: 75,
        imageUrl: "/images/signs/75.png",
        correctAns: 3,
        options: [
            "Air show ahead",
            "Air plane landing",
            "Route to Airport",
            "None of the above",
        ],
    },
    {
        id: 76,
        imageUrl: "/images/signs/76.png",
        correctAns: 2,
        options: [
            "No smoking",
            "No more than 3 minutes idling",
            "Idling is permitted",
            "No stopping more than 3 minutes",
        ],
    },
    {
        id: 77,
        imageUrl: "/images/signs/77.png",
        correctAns: 1,
        options: [
            "The bridge ahead lifts or swings to allow boats to pass",
            "Airport",
            "Hotel",
            "Narrow road ahead",
        ],
    },
];
